### ISSUE TITLE
Spring boot example 2.0.3

### ISSUE THREAD

**Issue by pawanw** [hawtio/hawtio#2498] opened 2018-08-14 19:44 UTC
I am trying to use the 2.0.3 spring boot example. Service starts fine and I am able to create a remote jolokia connection.   

![image](https://user-images.githubusercontent.com/22917330/44114221-2ef0f734-9fd0-11e8-9c7d-ebd3db245c56.png)

But when I click on the connect button, it not able to load the connection page. What am I missing here?
![image](https://user-images.githubusercontent.com/22917330/44114290-5e75e2c6-9fd0-11e8-8f15-3b500572449a.png)

Server logs -
2018-08-14 14:59:06.931 DEBUG 56764 --- [ XNIO-1 task-38] io.hawt.web.auth.SessionExpiryFilter     : Authentication disabled, received refresh response, responding with ok
2018-08-14 14:59:06.942 DEBUG 56764 --- [ XNIO-1 task-37] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/proxy/http/rv-qa6-ilas-01/22980/jolokia/], hawtio path is [proxy/http/rv-qa6-ilas-01/22980/jolokia]
2018-08-14 14:59:06.963 DEBUG 56764 --- [ XNIO-1 task-39] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/proxy/http/rv-qa6-ilas-01/22980/jolokia/], hawtio path is [proxy/http/rv-qa6-ilas-01/22980/jolokia]
2018-08-14 14:59:07.024  INFO 56764 --- [ XNIO-1 task-37] io.hawt.system.ProxyWhitelist            : Initial proxy whitelist: [*, 10.27.108.46, NC-DT-PWAT-01.CPEX.com, 127.0.0.1]
2018-08-14 14:59:07.178 DEBUG 56764 --- [ XNIO-1 task-39] io.hawt.web.proxy.ProxyDetails           : Proxying to http://rv-qa6-ilas-01:22980/jolokia/ as user: null
2018-08-14 14:59:07.178 DEBUG 56764 --- [ XNIO-1 task-37] io.hawt.web.proxy.ProxyDetails           : Proxying to http://rv-qa6-ilas-01:22980/jolokia/ as user: null
2018-08-14 14:59:07.182 DEBUG 56764 --- [ XNIO-1 task-39] io.hawt.web.proxy.ProxyServlet           : proxy POST uri: /hawtio/proxy/http/rv-qa6-ilas-01/22980/jolokia/ -- http://rv-qa6-ilas-01:22980/jolokia/
2018-08-14 14:59:07.182 DEBUG 56764 --- [ XNIO-1 task-37] io.hawt.web.proxy.ProxyServlet           : proxy POST uri: /hawtio/proxy/http/rv-qa6-ilas-01/22980/jolokia/ -- http://rv-qa6-ilas-01:22980/jolokia/
Hello Camel!
2018-08-14 14:59:08.612 DEBUG 56764 --- [ XNIO-1 task-25] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.629 DEBUG 56764 --- [ XNIO-1 task-42] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.637 DEBUG 56764 --- [ XNIO-1 task-32] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.641 DEBUG 56764 --- [ XNIO-1 task-43] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.643 DEBUG 56764 --- [ XNIO-1 task-33] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.646 DEBUG 56764 --- [ XNIO-1 task-44] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.649 DEBUG 56764 --- [ XNIO-1 task-45] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.652 DEBUG 56764 --- [ XNIO-1 task-46] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.655 DEBUG 56764 --- [ XNIO-1 task-47] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.658 DEBUG 56764 --- [ XNIO-1 task-41] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.660 DEBUG 56764 --- [ XNIO-1 task-50] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.663 DEBUG 56764 --- [ XNIO-1 task-51] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.665 DEBUG 56764 --- [ XNIO-1 task-52] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.668 DEBUG 56764 --- [ XNIO-1 task-54] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.673 DEBUG 56764 --- [ XNIO-1 task-53] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.676 DEBUG 56764 --- [ XNIO-1 task-40] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.680 DEBUG 56764 --- [ XNIO-1 task-55] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.682 DEBUG 56764 --- [ XNIO-1 task-48] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.685 DEBUG 56764 --- [ XNIO-1 task-49] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.688 DEBUG 56764 --- [ XNIO-1 task-59] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.691 DEBUG 56764 --- [ XNIO-1 task-58] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.738 DEBUG 56764 --- [ XNIO-1 task-56] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.741 DEBUG 56764 --- [ XNIO-1 task-63] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.744 DEBUG 56764 --- [ XNIO-1 task-60] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.747 DEBUG 56764 --- [ XNIO-1 task-61] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.750 DEBUG 56764 --- [  XNIO-1 task-2] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.753 DEBUG 56764 --- [  XNIO-1 task-1] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.756 DEBUG 56764 --- [ XNIO-1 task-62] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.759 DEBUG 56764 --- [  XNIO-1 task-4] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.762 DEBUG 56764 --- [ XNIO-1 task-57] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.764 DEBUG 56764 --- [ XNIO-1 task-64] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.770 DEBUG 56764 --- [  XNIO-1 task-3] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.773 DEBUG 56764 --- [  XNIO-1 task-6] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.777 DEBUG 56764 --- [  XNIO-1 task-7] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.780 DEBUG 56764 --- [  XNIO-1 task-5] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.784 DEBUG 56764 --- [ XNIO-1 task-12] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.787 DEBUG 56764 --- [ XNIO-1 task-11] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.790 DEBUG 56764 --- [ XNIO-1 task-14] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.792 DEBUG 56764 --- [ XNIO-1 task-15] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.795 DEBUG 56764 --- [ XNIO-1 task-13] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.798 DEBUG 56764 --- [ XNIO-1 task-10] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:08.800 DEBUG 56764 --- [  XNIO-1 task-8] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/], hawtio path is []
2018-08-14 14:59:10.809 DEBUG 56764 --- [ XNIO-1 task-19] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/jolokia/], hawtio path is [jolokia]
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] figuration$SilentSimpleUrlHandlerMapping : Matching patterns for request [/hawtio/jolokia/] are [/hawtio/jolokia/**]
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] figuration$SilentSimpleUrlHandlerMapping : URI Template variables for request [/hawtio/jolokia/] are {}
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] figuration$SilentSimpleUrlHandlerMapping : Mapping [/hawtio/jolokia/] to HandlerExecutionChain with handler [io.hawt.springboot.HawtioConfiguration$JolokiaForwardingController@79416dde] and 1 interceptor
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] onfiguration$JolokiaForwardingController : Returning view name 'forward:/jolokia?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false' for lookup path [/hawtio/jolokia/]
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] io.hawt.web.auth.AuthenticationFilter    : Handling request for path /jolokia
2018-08-14 14:59:10.810 DEBUG 56764 --- [ XNIO-1 task-19] io.hawt.web.auth.AuthenticationFilter    : No authentication needed for path /jolokia
2018-08-14 14:59:10.811 DEBUG 56764 --- [ XNIO-1 task-19] io.hawt.system.RBACRestrictor            : isAttributeReadAllowed(objectName = hawtio:type=Registry, attribute = UpdateCounter) = true
2018-08-14 14:59:10.811 DEBUG 56764 --- [ XNIO-1 task-19] io.hawt.system.RBACRestrictor            : isAttributeReadAllowed(objectName = hawtio:type=TreeWatcher, attribute = Counter) = true
2018-08-14 14:59:15.812 DEBUG 56764 --- [ XNIO-1 task-18] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/jolokia/], hawtio path is [jolokia]

**Comment by alexkieling** [comment] 2018-08-14 20:05
It's a bug. The new window URL is not right.

**Comment by alexkieling** [comment] 2018-08-15 20:17
Fixed on 2.x branch.

**Closed by alexkieling** 2018-08-15 20:17 UTC

**Comment by pawanw** [comment] 2018-08-17 20:10
Alex,
Thanks for quickly fixing the issue. But now it fails to load the index page.

![image](https://user-images.githubusercontent.com/22917330/44286699-9ca4aa80-a22f-11e8-9240-7f31642751b8.png)


2018-08-17 15:07:10.364 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Creating instance of bean 'org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator'
2018-08-17 15:07:10.365 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Finished creating instance of bean 'org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator'
2018-08-17 15:07:10.365 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Unable to locate RequestToViewNameTranslator with name 'viewNameTranslator': using default [org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@e0ebad4]
2018-08-17 15:07:10.365 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'viewResolver'
2018-08-17 15:07:10.366 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Creating instance of bean 'org.springframework.web.servlet.support.SessionFlashMapManager'
2018-08-17 15:07:10.368 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Finished creating instance of bean 'org.springframework.web.servlet.support.SessionFlashMapManager'
2018-08-17 15:07:10.368 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Unable to locate FlashMapManager with name 'flashMapManager': using default [org.springframework.web.servlet.support.SessionFlashMapManager@43e8269e]
2018-08-17 15:07:10.368 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Published WebApplicationContext of servlet 'dispatcherServlet' as ServletContext attribute with name [org.springframework.web.servlet.FrameworkServlet.CONTEXT.dispatcherServlet]
2018-08-17 15:07:10.368  INFO 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 9 ms
2018-08-17 15:07:10.368 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Servlet 'dispatcherServlet' configured successfully
2018-08-17 15:07:10.369 DEBUG 108332 --- [  XNIO-1 task-1] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/hawtio/index.html], hawtio path is [index.html]
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/hawtio/index.html]
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'requestMappingHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'viewControllerHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'beanNameHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'resourceHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'defaultServletHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'handlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'endpointHandlerMapping'
2018-08-17 15:07:10.373 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'hawtioUrlMapping'
2018-08-17 15:07:10.374 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /hawtio/index.html
2018-08-17 15:07:10.381 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/hawtio/index.html]
2018-08-17 15:07:10.381 DEBUG 108332 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /hawtio/index.html
2018-08-17 15:07:10.381 DEBUG 108332 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Did not find handler method for [/hawtio/index.html]
2018-08-17 15:07:10.381 DEBUG 108332 --- [  XNIO-1 task-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Matching patterns for request [/hawtio/index.html] are [/hawtio/**, /**]
2018-08-17 15:07:10.381 DEBUG 108332 --- [  XNIO-1 task-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : URI Template variables for request [/hawtio/index.html] are {}
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapping [/hawtio/index.html] to HandlerExecutionChain with handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], ServletContext resource [/app/], class path resource [hawtio-static/], class path resource [hawtio-static/app/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@d3d5094]]] and 1 interceptor
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'requestMappingHandlerAdapter'
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'httpRequestHandlerAdapter'
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'simpleControllerHandlerAdapter'
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'handlerAdapter'
2018-08-17 15:07:10.382 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/hawtio/index.html] is: -1
2018-08-17 15:07:10.384 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2018-08-17 15:07:10.384 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2018-08-17 15:07:10.386 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/error]
2018-08-17 15:07:10.386 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /error
2018-08-17 15:07:10.390 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/error]
2018-08-17 15:07:10.390 DEBUG 108332 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /error
2018-08-17 15:07:10.391 DEBUG 108332 --- [  XNIO-1 task-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public java.util.Map<java.lang.String, java.lang.Object> org.springframework.boot.actuate.endpoint.mvc.ManagementErrorEndpoint.invoke()]
2018-08-17 15:07:10.391 DEBUG 108332 --- [  XNIO-1 task-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'errorEndpoint'
2018-08-17 15:07:10.391 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/error] is: -1
2018-08-17 15:07:10.430 DEBUG 108332 --- [  XNIO-1 task-1] m.m.a.RequestResponseBodyMethodProcessor : Written [{timestamp=Fri Aug 17 15:07:10 CDT 2018, status=404, error=Not Found, message=Not Found, path=/hawtio/index.html}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@42b6d0cc]
2018-08-17 15:07:10.430 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2018-08-17 15:07:10.430 DEBUG 108332 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Successfully completed request

**Comment by alexkieling** [comment] 2018-08-19 13:10
@tadayosi @jamesnetherton could you please test this issue. I'm not able to reproduce the latest error.

**Comment by jamesnetherton** [comment] 2018-08-20 07:27
@alexkieling It works fine for me too.

**Comment by pawanw** [comment] 2018-08-21 20:55
@alexkieling I ran the hawtio-example-springboot from 2.x again and got the same result, not able to load the index page. May be something not right with the example?

**Comment by tadayosi** [comment] 2018-08-22 00:13
@pawanw Have you run `mvn clean install` first on your local machine?
