### ISSUE TITLE
Very slow startup for Hawtio 2 on a locked down network

### ISSUE THREAD

**Issue by strindberg** [hawtio/hawtio#2520] opened 2018-09-26 07:31 UTC
I am running Hawtio on a Windows machine on a very locked down network, where the machine cannot reach any Internet servers outside the internal network. With this setup, Hawtio (2.0.3) takes a long time (close to a minute) to start, hanging after the following lines are printed:

`About to start hawtio C:\Users\jholmberg\AppData\Local\Temp\184\hawtio-8367817375699755732.war
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT`

I assume it is trying to do some sort of network lookup that fails after a timeout. Is there an option I can use to prevent this lookup and thus achieve a quicker startup time?

I normally start hawtio like this:

`java -Dhawtio.proxyWhitelist=* -Dhawtio.offline=true -Dhawtio.proxyDisableCertificateValidation=true -jar hawtio-app-2.0.3.jar --port 9877`

**Comment by tadayosi** [comment] 2018-09-26 09:13
Probably it's a duplicate of #2466

**Closed** 2019-08-20 02:33 UTC

**Comment by strindberg** [comment] 2019-08-20 07:35
Why was this issue closed? The problem still remains and renders Hawtio virtually unuseable on a restricted network.

**Comment by tadayosi** [comment] 2019-08-20 07:37
I thought it's a duplicate of #2466, isn't it?  We can work on the issue at #2466 then.
