### ISSUE TITLE
Monitoring multiple servers in kubernetes

### ISSUE THREAD

**Issue by mariuszkopowski** [hawtio/hawtio#2636] opened 2020-06-19 09:04 UTC
Hi All
I have currently few servers with Artemis, Service Mix etc. all running on Kubernetes cluster.
Without kubernetes I was able to have one hawtio running where I could connect to all remote hosts. 
But in kubernetes I'm not able to connect to any of the hosts. I was trying via internal IP of containers, internal DNS of the pod and service name. And it doesn't work. When I make a ping on the Hawtio container it connects to any of the servers. I have also tried telnetting to the addresses and it work.

Is it possible at all to do that ? or the connection have to be to addresses that I have access to from my PC ?

**Comment by tadayosi** [comment] 2020-06-23 01:18
@mariuszkopowski That's what hawtio-online is expected to do, but as you are aware it only supports OpenShift at this moment: https://github.com/hawtio/hawtio-online/issues/23 The problem is that we don't have much resource to work on the issue now, but please keep an eye on it.

**Comment by tadayosi** [comment] 2022-02-03 05:28
Closing as now hawtio-online supports k8s too.

**Closed by tadayosi** 2022-02-03 05:28 UTC
