### ISSUE TITLE
Hawt.io embedded in spring boot app cannot use different web context

### ISSUE THREAD

**Issue by heevy** [hawtio/hawtio#2138] opened 2016-05-23 08:28 UTC
I have spring boot application which is packaged as WAR file. This application contains embedded hawt.io version 1.4.65 . Hawt.io has beed embedded following https://github.com/hawtio/hawtio/tree/master/hawtio-sample-springboot .

Everything is working correctly when i deploy application to Tomcat ROOT (/) . But when i deploy application to specific web context(for example /myapp) i am not able to access hawt.io GUI anymore. It every time forwards me to login (please note that i have disabled authentication and no login is required when application is deployed in /).

**Comment by prathap2k** [comment] 2016-10-20 21:18
Facing the same problem. Voting this up.

**Comment by helpermethod** [comment] 2016-10-25 14:59
Same here. With respecting the application context hawtio is pretty useless.

**Comment by roband** [comment] 2016-11-10 15:04
I had the same problem and fixed it by making a one-line change in SessionExpiryFilter.java and RedirectFilter.java.

At the top of the process() method in both:

Change the first:
String uri = request.getRequestURI();
To:
String uri = request.getRequestURI().substring(request.getContextPath().length());

Works for me. If it works for you as well I'll do a pull-request and hopefully we get it merged into the next release.

**Comment by tadayosi** [comment] 2017-03-03 01:56
Hmm, I don't think this is a correct fix:
> String uri = request.getRequestURI().substring(request.getContextPath().length());

 Looking at the code, it just effectively always skips the authentication, so you'll face troubles when you've enabled authentication.

**Comment by tadayosi** [comment] 2017-03-03 08:11
See also: https://github.com/hawtio/hawtio/pull/2270#issuecomment-283017183

@vitaliylevashin Can you share with us the detailed steps to reproduce your issue here?

**Comment by tadayosi** [comment] 2017-03-03 10:07
Please check if this commit 857c45cd9d2da53612c1a4ddfc174211fd6b1d0a fixes the issue.

**Comment by vitaliylevashin** [comment] 2017-03-03 12:14
Hi @tadayosi,
I've tried your fix, but results are the same - routing seems broken.
In order to reproduce just add **server.contextPath: /app** to application.properties file.

Request to **http://localhost:10000/app/hawtio/index.html** will be routed incorrectly and you will end up in **http://localhost:10000/app/hawtio/index.html#/login**

Maybe my assumptions on context extraction from URI is wrong? I think it will be easier to represent my expectations in unit tests. Please check this commit -https://github.com/vitaliylevashin/hawtio/commit/1ddbaf36e90b22e9820cb7499059dd712409f54d
I've extracted common logic into separate class and covered it with unit tests. Some of them represent expected behavior for empty contextPath and some - for the custom one. 
Could you please point out on my mistake(s) in these tests.

**Comment by tadayosi** [comment] 2017-03-06 07:22
@vitaliylevashin Thanks for the info. Then I guess what's wrong with your use case is this class:
https://github.com/hawtio/hawtio/blob/hawtio-1.5.0/hawtio-springboot/src/main/java/io/hawt/springboot/HawtioConfiguration.java
Maybe we should not hardcode the prefix `/hawtio` in this class and instead utilise `server.contextPath: /hawtio` in `application.properties`. Then by changing `server.contextPath` you should be able to change the context root to http://localhost:10000/app/index.html.

I haven't tried this idea yet; please feel free to try it at your end.

**Comment by jiridudekusy** [comment] 2017-03-06 10:30
@tadayosi I dont think that you should rely on server.contextPath property. You can also deploy Spring Boot application to normal tomcat (or other web container) as WAR.

**Comment by tadayosi** [comment] 2017-03-06 10:41
@jiridudekusy I don't really understand why we shouldn't rely on `server.contextPath`. Firstly, what do you think would happen if we apply the changes to `HawtioConfiguration` outlined above?  Secondly, why do you really need to deploy hawtio-embedded Spring Boot application?  For normal Tomcat or other web containers, why would the normal `hawtio-web.war` not work for you?

**Comment by sueastside** [comment] 2017-03-06 10:55
I second jiridudekusy, at a client we too have a spring boot application with embedded hawtio that needs to be deployed to an application server for some of their legacy (but not going away any time soon) environments.

**Comment by heevy** [comment] 2017-03-06 11:01
@tadayosi My origin idea ( jiridudekusy=heevy=me ;) )  behind this issue is that i will produce spring boot executable war file which can be either deployed into web container or launched as spring boot application and in both scenarios  you would have hawtio enabled in your application in same way as jolokia (http://localhost:8080/app/jolokia)... so hawt.io should be accessible on url (http://localhost:8080/app/hawtio/index.html) . Deployment of hawtio-web.war is workaround which we are using currently but it is not preferred solution for me.

**Comment by tadayosi** [comment] 2017-03-06 11:34
@heevy Let me make sure, how do you configure the context path `/app` in this case?  Using `server.contextPath = /app` or just naming your war as `app.war`?

IMO http://localhost:8080/app/hawtio/index.html is not a correct URL anyway, as `hawtio-system` stuffs including `SessionExpiryFilter` all expect URLs in the form of `/<hawtio root context path>/<sub context>/...`. Only the default root context path is `/hawtio`. So if you change the context path to `/app` then a correct URL hawtio expects would be http://localhost:8080/app/index.html. Does that make sense?

**Comment by vitaliylevashin** [comment] 2017-03-06 12:06
@tadayosi 
Actually, I do like that hawtio has it's own context (/hawtio). This allows us to separate original SB application's resources from the ones provided by hawtio. 
For example:
- http://localhost:8080/app/myapp/
- http://localhost:8080/app/hawtio/

Also, imagine that we would need to provide our own welcome page at http://localhost:8080/app/index.html. I guess, this won't be possible in proposed approach.

**Comment by tadayosi** [comment] 2017-03-06 12:22
@vitaliylevashin I don't think that's how hawtio works.  I strongly believe what you are really looking for is a fix for this issue #1972.

So the entire issue here is a duplicate of #1972?  Is there anything unique in this issue?

**Comment by heevy** [comment] 2017-03-06 13:43
@tadayosi It is not completely duplicate but these two issues defines how hawt.io should behave when it is embedded in spring Boot Application. We can summarise it to following points.

- embedded Hawt.io evertime should use its own context path which is "<my app context>/hawtio" by default. It would be nice to make this configurable.
- When you run your project as Spring Boot application it must honor the settings from application.properties (#1972).
- when you deploy your project as Spring Boot WAR file to web container it must honor the container configuration (ip, ports, context path)

**Comment by tadayosi** [comment] 2017-03-07 01:18
Thanks @heevy for the summary!  It looks good to me. Only one thing I'd like to add to it is:

- The fix must not break anything in the classical `hawtio.war` deployment.

Let's see how we can fix hawtio to meet all those requirements above.

**Comment by evmin** [comment] 2017-06-24 06:42
+1

**Comment by vspiliop** [comment] 2017-11-10 17:56
+ 1

**Comment by wigbam** [comment] 2018-02-06 14:16
+1

**Closed** 2018-03-12 02:32 UTC
