### ISSUE TITLE
Connecting to a remote JVM opens the same tab instead

### ISSUE THREAD

**Issue by HeavyMetalPirate** [hawtio/hawtio#3317] opened 2024-03-20 13:49 UTC
Kinda struggling the last couple days trying to pin an issue with remote connections after upgrading from Spring Boot 2.7 to Spring Boot 3.2.

I have the following setup here:

- Spring Boot Admin Server with Hawt.io console attached
- Several applications with Apache Camel
- Spring Actuator for application monitoring on all apps
- Jolokia enabled through Actuator on all apps

The main goal is to have a central administrative interface for Apache Camel using a single hosted Hawt.io console that connects to the remote apps.

In the Hawt.io console I have set up the connections to the remote agents manually, testing the connection works just fine.
On my Spring Boot 2.7 stack  with Hawt.io 3 opening a remote connection opens a new tab with a console showing the data from the remote agent.
On the Spring Boot 3.2 stack with Hawt.io 4 however the new opened tab shows the same local console. 

I found out that if I switch to a different plugin like JMX on the local console then add the 'con' parameter to the browser URL I now get the remote console of the connection provided. I can then proceed to manage the remote JVM like normal including Camel which is missing on the local console.

The current stack as follows:
- Spring Boot 3.2.0
- Hawt.io using hawtio-springboot 4.0.0-RC1
- jolokia-support-spring 2.0.1 on remote apps via Spring Actuator

Is there anything I'm missing here?

Regards

**Comment by tadayosi** [comment] 2024-03-21 05:31
Hi, your configuration sounds fine to me. 

> In the Hawt.io console I have set up the connections to the remote agents manually, testing the connection works just fine.
> On my Spring Boot 2.7 stack with Hawt.io 3 opening a remote connection opens a new tab with a console showing the data from the remote agent.
> On the Spring Boot 3.2 stack with Hawt.io 4 however the new opened tab shows the same local console.

I still don't follow how you use Hawtio with Spring Boot here. Normally, Hawtio is embedded with a Spring Boot app so you won't need to explicitly use the Connect plugin to connect to a remote app. Or do you want to manage other remote apps from the hosting Spring Boot app?

You can also try the example. If it works as you expect, then you might want to find what are the differences between your app and the example.
https://github.com/hawtio/hawtio/tree/hawtio-4.0.0-RC1/examples/springboot

**Comment by HeavyMetalPirate** [comment] 2024-03-21 08:02
> Or do you want to manage other remote apps from the hosting Spring Boot app?

Yes, this is the use case, sorry for being a bit unclear. Trying to connect opens a new tab but I still get shown the same content from the hosting app, not the remote. I can however get to the remote app if I add the query param `con=<connection name>` manually on a plugin tab that is also available on the remote app.

I will try the examples later today and will get back at you, thanks for the pointer.

**Comment by tadayosi** [comment] 2024-03-21 08:13
For the embedded mode (used in Spring Boot or Quarkus), the Connect plugin is disabled by default, because it's not the primary use case. But if you want to re-enable it you can add `hawtio.disableProxy = false` in `application.properties` and the Connect tab reappears.

**Comment by HeavyMetalPirate** [comment] 2024-03-21 09:22
Thanks for the input. I have set that property already as I do have the connect tab on the hosting app. I also have successfully configured connections to remote apps manually and testing the connections is successful. The only issue is after clicking the "Connect" button, the new tab that opens will still show the hosting console, not the remote console as expected.

**Comment by tadayosi** [comment] 2024-03-22 06:07
@HeavyMetalPirate Thanks, now I totally see what you are saying. I reproduce the same issue with me, and indeed it's a bug. We'll fix it. Thank you for your reporting!

Meanwhile, one possible workaround is to use Hawtio JBang instead of a SB app for the centralised console. Since it's not attached to any embedded Jolokia endpoint, it shouldn't have the same issue.
https://github.com/hawtio/hawtio?tab=readme-ov-file#running-from-cli-jbang

**Comment by HeavyMetalPirate** [comment] 2024-03-22 08:58
Thank you for your investigations and assistance. I can confirm the proposed workaround is working as intended, thank you.

**Comment by grgrzybek** [comment] 2024-04-10 08:20
I've created a duplicate #3379 issue:

connecting to remote Jolokia opens new tab with main JMX view, but the network tab shows mixed `jolokia` and `proxy` requests.

No `connect.currentConnection` session storage entry (or `con` parameter) for remote view is available.

Only browsing directly to URL like http://localhost:10001/actuator/hawtio/jmx?con=discover-3e3abc88-jvm shows the remote view.

I'm closing #3379.

**Comment by grgrzybek** [comment] 2024-04-16 15:06
I found the reason why it doesn't work. When we click "connect" in _main_ Hawtio tab, new tab is opened with URL like `http://localhost:10001/actuator/hawtio/?con=discover-3e3abc88-jvm` - this request however is not handled by some running JavaScript code in the browser, because it's an initial request, which goes to server. In response we're however getting:
```
HTTP/1.1 302 Found
Connection: keep-alive
Location: http://localhost:10001/actuator/hawtio/index.html
Content-Length: 0
Date: Tue, 16 Apr 2024 15:03:35 GMT
```
(copied from network tab in browser), so `con` parameter is lost.

**Comment by tadayosi** [comment] 2024-04-17 05:06
@grgrzybek 
> I found the reason why it doesn't work. When we click "connect" in main Hawtio tab, new tab is opened with URL like http://localhost:10001/actuator/hawtio/?con=discover-3e3abc88-jvm - this request however is not handled by some running JavaScript code in the browser, because it's an initial request, which goes to server.

Great insight!

So the fix is reserving the `con` parameter (and anything else as well) when redirecting to `/index.html`?

**Comment by grgrzybek** [comment] 2024-04-17 07:42
PR: #3397

**Closed** 2024-04-17 07:56 UTC
Labels: kind/bug
