### ISSUE TITLE
"mvn jetty:run" in hawtio-web shows ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2276] opened 2017-03-23 01:13 UTC
Running `mvn jetty:run` under hawtio-web shows a bunch of `ArrayIndexOutOfBoundsException` like this:
```
[WARNING] Problem processing jar entry io/hawt/util/Strings.class
java.lang.ArrayIndexOutOfBoundsException: 4998
	at org.objectweb.asm.ClassReader.readInt(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:899)
	at org.eclipse.jetty.annotations.AnnotationParser$2.processEntry(AnnotationParser.java:857)
	at org.eclipse.jetty.webapp.JarScanner.matched(JarScanner.java:161)
	at org.eclipse.jetty.util.PatternMatcher.matchPatterns(PatternMatcher.java:100)
	at org.eclipse.jetty.util.PatternMatcher.match(PatternMatcher.java:82)
	at org.eclipse.jetty.webapp.JarScanner.scan(JarScanner.java:84)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:869)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:884)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.parseWebInfLib(AnnotationConfiguration.java:422)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:120)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:468)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1237)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365)
	at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:523)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by skarsaune** [comment] 2017-04-19 20:25
The jetty version does not seem to handle recently compiled java class files well. 
The warning disappears when jetty is updated to 9.2.10.v20150310 as the 2.x branch. 
This however introduces a new problem caused by the test dependency on the jetty-maven-plugin that loads the same classes more than once since the jetty plugin config also loads test resources. 
This can be fixed by removing the test dependency on the jetty-maven-plugin.
However that gives problems with the src/test/java/io/hawt/sample/Main.java class that uses resources from the plugin.
A couple of questions:

1. Is the Main class useful? Use of a maven plugin resources to launch jetty does not seem like good practice. The dependency is problematic and there seem to be better launchers elsewhere in hawtio. 

1. The included test resources in the jetty-plugin does not seem to have much effect when launching with mvn jetty:run. It is not that clear what all the test dependencies and code is used for.

I have a branch that upgrades jetty and removes plugin dependency and Main class, should I create a pull request to illustrate this?

**Comment by tadayosi** [comment] 2017-04-20 01:32
Thanks for the detailed investigation. Contributions are always welcome!

1. I personally don't use `mvn exec:java` but mostly use `mvn jetty:run` for hawtio development, so I could live without it. However, according to http://hawt.io/building/index.html `mvn exec:java` and `Main.java` seem to serve as an entry point for hawtio development, which work as a showcase for most built-in plugins. I'm not sure but someone might be still using it for hacking hawtio.

2. I quite often use `mvn -Dhawtio.authenticationEnabled=true jetty:run` so at least `hawtio-web/src/test/resources/users.properties` is essential for my workflow.

I agree that we need some overhaul around these so we can use up-to-date Jetty versions.

**Comment by skarsaune** [comment] 2017-04-20 08:31
Thanks for pointing that out. Will investigate further .

**Comment by skarsaune** [comment] 2017-04-23 20:27
Investigation points to quite a few changes just in order to sort out this tiny nuisance. Hopefully it can be of some use when if one decides to upgrade jetty in hawtio. 
Working example here: https://github.com/skarsaune/hawtio/commit/c806b1833b89117373ec749a37a994e2c470b4f5

1. Upgrade jetty to 9.4.2.v20170220
1. group id "org.eclipse.jetty.aggregate" -> "org.eclipse.jetty"
1. had to upgrade javax.servlet.api 2.5.0 -> 3.1.0, this may be a bit drastic, as it could introduce dependencies in hawtio that would not run in older containers. Perhaps better left as is and overridden in specific modules that need to launch jetty to test?
1. PROBLEM: livereload-jvm 0.2.0 is tied to jetty 8. There is little activity in this project. Have submitted PR to get a release that supports jetty 9: https://github.com/davidB/livereload-jvm/pull/9
1. do not include all test resources in hawtio-web jetty:run , instead include src/test/resources 
1. Upgraded jboss-as-maven-plugin to 7.9.Final, due to runtime errors. 

Result
mvn exec:java : OK
mvn -Dhawtio.authenticationEnabled=true jetty:run OK
mvn tomcat6:run OK
mvn  tomcat7:run OK
mvn jboss-as:run Startup error resolved, but appears to hang. (Also seems to hang in master)

**Closed** 2020-09-04 03:04 UTC
Labels: bug
