### ISSUE TITLE
Hawtio treeview collapses after refreshing

### ISSUE THREAD

**Issue by Cecilio-Alvarez** [hawtio/hawtio#1942] opened 2015-04-09 12:00 UTC
Hawtio camel tab treeview collapses after a while and there is no more possible to expand it.

Hawtio 1.45.5 and 1.45.8
Camel 2.14.1

Thanks

**Comment by davsclaus** [comment] 2015-04-14 11:25
What do you mean by refreshing? Do you press F5 on the browser or click a button, or just leave the computer idle and do nothing?

Maybe you can paste some screenshots to better highlight the issue

**Comment by Cecilio-Alvarez** [comment] 2015-04-15 08:51
When hawtio refreshes itself, if I disable the auto refresh still happens after a while

![image](https://cloud.githubusercontent.com/assets/5716095/7155045/d6292132-e35b-11e4-8437-8135f540ac3c.png)

After it refreshes, the tree view collapses and can't be open again.

![image](https://cloud.githubusercontent.com/assets/5716095/7155209/0ab27330-e35d-11e4-9276-28cfc61819b5.png)

Thanks
Cecilio

**Comment by davsclaus** [comment] 2015-04-17 08:30
There was a fix in hawtio to make the tree "remember" its state. I wonder if that fix could cause this issue.

When you see the tree as empty. Can you try the JMX plugin and see if you can find the Camel's there? And if not, then maybe try from jconsole to see?

I assume the Camels are still in the JVM and its a bug in hawtio tree, maybe introduced by that change I spoke about.

Have you used older versions of hawtio where there was no such problem?

**Comment by davsclaus** [comment] 2015-04-17 08:34
This is the tree change
https://github.com/hawtio/hawtio/commit/ebe6724f69a5b0b227407bf5d3acd5686425acb5

**Comment by Cecilio-Alvarez** [comment] 2015-04-22 08:58
Yes, when I refresh manually -F5- or I go to the JMX plugin and come back to Camel, it appears again. I've seen this in versions since 1.3. 
We have many ActiveMQ/Camel/Hawtio installation and this issue sometime happens.

**Comment by geertvanheusden** [comment] 2015-06-17 14:15
We are having the same issue on all of our servers. It occurs a lot on camel instances with high traffic throughput.
Is there a way to enable logging in Hawtio so we can provide you with more info to pinpoint this issue?

**Comment by Cecilio-Alvarez** [comment] 2015-06-17 14:35
I couldn't figure this out but in one of the servers the problem went away after setting connection pooling for ActiveMQ in Camel, It seems to me that without this the huge number of threads created was the problem. You can check if is that in the threads tab.

**Comment by davsclaus** [comment] 2015-06-17 14:46
Ah check the tree counter in JMX in io.hawtio domain. There is a mbean that has an attribute with a counter. This counter is ++ when the JVM adds/removes mbeans. And when this happens the UI state may need to refresh / update.

There used to be a bug in AMQ that causes many add/remove mbeans. 

And yeah for AMQ always use pooling.

**Comment by geertvanheusden** [comment] 2015-06-18 08:16
The TreeWatcher counter property is at 1202. In our case we only use Camel routes, no AMQ.

**Comment by davsclaus** [comment] 2015-06-18 08:18
Does it stay the same eg keep being 1202 and even so the tree collapses?

**Comment by geertvanheusden** [comment] 2015-06-18 08:20
Yes, it stays the same.

**Comment by nelreina** [comment] 2015-06-18 16:54
I have the same issue when viewing the AMQ and this is annoying when I am monitoring or resolving some production issue.
It get the point that I created my own front end solution. 

Why does the tree structure need to refresh every x minutes. I think It will be a better user experience if you get only the data to build tree when user hit the page and when someone click on one of the items, get the data from that item.

**Comment by davsclaus** [comment] 2015-06-18 17:10
Instead of building your own its maybe better to contribute and improve on hawtio. Its FOSS.

**Comment by nelreina** [comment] 2015-06-18 17:20
I did not build it in Java. 

I created a nodejs application with 5 seconds interval that push the jolokia data thru web socket to the listen  clients, and when You need details of e.g. a queue the client will unsubscribe and subscribe to a details socket for that particular queue/ topic . If no one is listening to socket feed the timer will stop on the server.

**Comment by geertvanheusden** [comment] 2015-06-19 11:15
![screen shot 2015-06-19 at 13 10 33](https://cloud.githubusercontent.com/assets/1923423/8252282/d8f60720-1684-11e5-8cf5-6245a0d57e9f.png)
During startup I always get the following messages. Could this be related?
I am using the offline version of hawtio. The context which gives an error (on the right in the screenshot) changes from time to time.

**Comment by Cecilio-Alvarez** [comment] 2015-06-19 11:24
Did you add the hawtio.offline property? Maybe this is related.

**Comment by geertvanheusden** [comment] 2015-06-19 15:18
I just did but no difference.

**Comment by davsclaus** [comment] 2015-06-19 15:31
@nelreina btw hawtio 2.x is not so java based, its pure bower / grunt / typescript / javascript and all that. And its much more pluggable so the hawtio distro is not a big size. 

Maybe reach out to @gashcrumb on irc on #hawtio on freenode as he is main developer on it. We would love to make the tree / table or sometning nicer as ui, also if you have a very large number of queues maybe the tree structure is not ideal.

**Comment by nelreina** [comment] 2015-06-19 17:37
Tnx @davsclaus I will definitely take a look at hawtio 2.x. And no in my app I did not build a tree structure just a list of al queues with some stats , and and when you click on the queue , I put the most used actions by us like purge etc.. .

**Comment by geertvanheusden** [comment] 2015-06-24 09:45
I enabled DEBUG logging and came up with the following result. Not sure if it is helpful...

![screen shot 2015-06-24 at 10 28 24](https://cloud.githubusercontent.com/assets/1923423/8327112/384aa868-1a66-11e5-8889-69f9c32c9065.png)

Full log:
```
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
Camel version 2.15.1
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=2&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[Core] JMX tree has been loaded, data:  Object {JMImplementation: Object, Users: Object, jmx4perl: Object, IBM WebSphere MQ classes for JMS: Object, com.sun.management: Object…}
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Camel] Reloading the tree for filter: undefined
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Core] Executing task:  ConParam  with parameters:  [Object, "http://.../hawtio/jmx/attributes?tab=camel&nid=camelContexts", "http://.../hawtio/jmx/attributes?tab=came…t-org.apache.camel-lidoEffoutRouterContext-routes"]
[Core] Executing task:  UpdateSession  with parameters:  [Object, "http://.../hawtio/jmx/attributes?tab=camel&nid=camelContexts", "http://.../hawtio/jmx/attributes?tab=came…t-org.apache.camel-lidoEffoutRouterContext-routes"]
[Core] Updating session expiry
[Core] Made request
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[Core] Using view partial: app/camel/html/layoutCamelTree.html
[Perspective] Plugin dashboard excluded in perspective container
[Perspective] Plugin dashboard excluded in perspective container
[JMX] nid:  camelContexts
[Core] hash changed from  ?tab=camel&nid=root-org.apache.camel-lidoEffoutRouterContext-routes  to  ?tab=camel&nid=camelContexts
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/refresh".
[Core] Updated session, response:  ok
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
[RBAC] Enriched workspace tree:  a {title: "MBeans", key: "root", typeName: null, children: Array[12], folderNames: Array[0]…}
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
XHR finished loading: POST "http://.../hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false".
```

**Comment by geertvanheusden** [comment] 2015-07-01 11:36
Any thoughts on this? Hawtio is becoming unusable for us.. :-(

**Comment by gashcrumb** [comment] 2015-07-01 13:46
Wonder if it has anything to do with this line:

```[Camel] Reloading the tree for filter: undefined```

also, does typing in the filter or hitting the expand all/collapse all icons help at all?

Will see if I can get this to reproduce locally.

**Comment by gashcrumb** [comment] 2015-07-01 14:13
It is strange that there'd be a call with a ```maxDepth``` setting of ```2``` amidst all of the other calls, but even setting that to 2 I still get a camel tree, including when I force a JMX tree update.  @geertvanheusden can you confirm the hawtio version you're using?

**Comment by geertvanheusden** [comment] 2015-07-01 17:11
No, using the expand all/collapse or entering a filter value doesn't help.

I am using the following version (offline edition):
hawtio version: 1.4.47
jolokia version: 1.2.3
server version: Apache tomcat 7.0.57

**Comment by gashcrumb** [comment] 2015-07-01 17:26
K.  I've not had much luck reproducing it so far, at least against a build on master.  Have you tried a more recent version by any chance?  Think we're at 1.51 on the site, so that's a fair number of fixes that have gone in since then.  If you're going to try it, make sure you clean your browser cache after installing the new version.  I'd also maybe recommend clearing your local storage, it's under Preferences / Reset just to be on the safe side.

**Comment by geertvanheusden** [comment] 2015-07-01 17:28
I'll give it a try tomorrow and let you know.

Thanks for investigating this.

**Comment by davsclaus** [comment] 2015-07-01 18:10
Also upgrade jolokia - as Roland did some fixes in the 1.3.1 about some limitations that causes jolokia to not return all data, but only chunks of it.

**Comment by geertvanheusden** [comment] 2015-07-02 08:54
I just did a build of the latest master and installed it on our servers, removed the browser cache and did a reset just to be safe.
At first sight it seems more stable but this could be due to the fact that there is less traffic on our camel routes.
I will monitor the servers today and let you guys know if there is an improvement.

**Comment by geertvanheusden** [comment] 2015-07-07 09:24
It's definitely more stable than before!
Is there a new release planned for Hawtio that includes the upgrade of jolokia to 1.3.1?

**Comment by davsclaus** [comment] 2015-07-07 09:26
Yay, lets try to get 1.4.52 out then.

**Comment by davsclaus** [comment] 2015-07-07 09:32
@grgrzybek is doing the 1.4.52 release today

**Comment by geertvanheusden** [comment] 2015-07-07 09:33
@davsclaus @grgrzybek Cool thx!

**Comment by davsclaus** [comment] 2015-07-07 13:18
1.4.52 is now in maven central for download.

**Comment by spiner2000** [comment] 2015-08-03 09:41
Hello! Issue is still present, is there any temp solutions?

**Closed** 2015-08-21 05:56 UTC
Labels: bug, camel, ui
