### ISSUE TITLE
Wrong version of jolokia

### ISSUE THREAD

**Issue by hchehade** [hawtio/hawtio#1725] opened 2014-11-10 09:43 UTC
Jolokia V122 is causing multitude of errors. Many entries in JMX and Camel are missing.
Setting the dependency to jolokia V121 would resolve these problems.

**Comment by davidflam** [comment] 2015-01-28 20:32
Same problem as @hchehade, most of the entries inside the org.apache.camel JMX domain are missing. We are running about 1000 routes inside Apache ServiceMix 5.4.0 with hawt.io version 1.4.46. When I downgrade hawt.io to version 1.4.4 it works as expected. One more information, when issuing a GET request to http://<myip>:8181/hawtio/jolokia/list I get different response sizes. Jolokia serialization issues?

**Comment by davsclaus** [comment] 2015-02-13 12:13
Was this problem related to jolokia 1.2.2+ upgraded to a newer json simple

master
https://github.com/rhuss/jolokia/blob/master/pom.xml#L384

1.2.1
https://github.com/rhuss/jolokia/blob/v1.2.1/pom.xml#L385

1.2.2
https://github.com/rhuss/jolokia/blob/v1.2.2/pom.xml#L384

So upgrading from json simple 1.1 to 1.1.1 maybe likely caused this problem? 

If anyone able to consistently reproduce, then you are welcome to try with jolokia 1.2.1 and then force it to use json simple 1.1.1 so that would be the only change, and then see if that causes the problem.

And if so we could get it reported to json simple, and maybe jolokia in the mean time could downgrade to 1.1 so it works

**Comment by chrislovecnm** [comment] 2015-02-24 00:35
Can we get it documented which version of jolokia to use with which version of hawtio :)

**Comment by hchehade** [comment] 2015-02-25 08:13
actually it is working fine with 1.2.1

**Comment by rhuss** [comment] 2015-03-04 13:32
I just created a SNAPSHOT from 1.2.2 with json-simple-1.1.1 replaced by json-simple-1.1 (nothing changed otherwise). You can refer to it as `jolokia-1.2.2-json-simple-1.1-SNAPSHOT`.

The WAR agent can be directly downloaded from [maven central](https://oss.sonatype.org/content/repositories/snapshots/org/jolokia/jolokia-war/1.2.2-json-simple-1.1-SNAPSHOT/).

@chrislovecnm , @davidflam, @hchehade, @fliot: Since I really can't reproduce it myself (sorry, don't have the appropriate amount of Came routes ;-) I need your help. Could you please try this [agent](https://oss.sonatype.org/content/repositories/snapshots/org/jolokia/jolokia-war/1.2.2-json-simple-1.1-SNAPSHOT/jolokia-war-1.2.2-json-simple-1.1-20150304.131602-1.war) (or the JVM variant from the same location, which also contains the json-1.1-simple.jar) with your setup ? This would be awesome !

Thanks a lot !

**Comment by rhuss** [comment] 2015-03-06 06:53
Since this is a Jolokia issue I opened an issue over there (rhuss/jolokia#187). Please let's continue there.

**Comment by fliot** [comment] 2015-03-06 09:35
Camel routes display (around 200 routes), perfectly works on my build (hawtio 1.4.45, jolokia 1.2.1).

I just tested with jolokia 1.2.2-json-simple-1.1-SNAPSHOT, and unfortunatelly I must advise it doesn't work (as it doesn't work with jolokia 1.2.2).

**Comment by rhuss** [comment] 2015-03-10 16:22
Thanks for the feedback, this is quite helpful. I will have closer look to the code diff then.

**Comment by rhuss** [comment] 2015-03-10 20:52
Indeed the serialization stuff has been changed slightly between 1.2.1 and 1.2.2. However, I still can't repdoruce the issue. I introduced a large lists in the [AttributeChecking](https://github.com/rhuss/jolokia/blob/master/it/core/src/main/java/org/jolokia/it/AttributeChecking.java#L155) MBean and tried it with really large lists, but they are only truncated if `maxCollectionSize` is exceeded. BTW, `maxCollectionSize` for the WAR agent has a hard limit of 1000 which cannot be overridden. But this was already the case for 1.2.1, though this shouldn't be the problem. 

Since I'm not that fluent in Camel yet, could someone please create a small, self-contained WAR which creates a large number of routes during init (1000 or so) so that I could examine the situation locally ? 'would be very helpful and shouldn't be much work.

thanks ....

**Comment by davsclaus** [comment] 2015-03-13 07:51
I created a bit camel project based on the Apache Camel Servlet Tomcat example.

Its hosted in github at
https://github.com/davsclaus/bigcamel

You can build from source and deploy the war to tomcat.

I also noticed that in hawtio the number of routes listed are not all of them, but a bit strange with routes from the begging, and then a chunk of routes from the end etc.

The app has one main route which is the the helloRoute. And then when you add new routes they are named route-1, route-2 ...

**Comment by davsclaus** [comment] 2015-03-13 07:59
And you can also list all the routes using, and then compare with jolokia
http://localhost:8080/bigcamel-1.0/camel/hello?list=true

**Comment by rhuss** [comment] 2015-03-13 09:06
Thanks a lot, @davsclaus  !

Good news: I could reproduce the problem with 500 routes. Interestingly, the list of route MBeans is not truncated but there are gaps in the list (e.g `route-103` is missing ...). Very interesting ;-)

Hope I can nail it down over the weekend so that we finally have a solution for that.

**Comment by rhuss** [comment] 2015-03-13 09:29
BTW, its start with 167 added routes and is completely deterministic and reproducible (route-92 is missing then in 1.2.2 but not 1.2.1). 

Nice somehow.

**Comment by davsclaus** [comment] 2015-03-13 09:49
@rhuss and I though only OSGi could drive you mad with non deterministic behavior based on factors from the current lunar position and whether its a leap year

**Comment by rhuss** [comment] 2015-03-13 10:51
Ok, got it finally.

The point is, that between 1.2.1 and 1.2.2 a bug was fixed accidentally (well, doesn't happen very often ;-): Jolokia has some options which influences the JSON serialization. One of them is `maxCollectionSize` which is used when serializing collections. By default this is set to 1000 so that collections are trunctated at that size. If this value is 0, no truncation happens. This was introduced as a safety net.

This truncation worked for any collections in 1.2.1 except for `JSONObject` and `JSONArray` (which is a special map which knows how to serialize to JSON). That was a bug. In 1.2.2 I unified the serialization of `JSONObject` and `Map` and only do a serialization for a `Map` (where truncation works).

Since the `LIST` operation creates internally a JSONObject for the meta data to return which then gets serialized like any other value to JSON, this bug affects the list operation, too: 

**As soon as the number of MBeans within a domain exceed `maxCollectionSize` which has the default of 1000, the list of MBeans is truncated** (the point of truncation is arbitrary since it happens during an loop over a map's keys).

This is of course not a good solution. There are several ways how to fix that:

* Increase the default limit to 10000 (or something smaller). Of course, this problem will occur here as well then. But I wonder whether this is a problem in reality, having more than 10000 MBeans registered in an JMX domain is really insane.
* No limitation for LIST operations (or a separate limitation).
* No hard limit for collections so that a "?maxCollectionSize=0" can be added to a single request. Currently the default limit of 1000 (which can be changed of course e.g. in web.xml or during startup of the agent) is hard so that a query parameter can only redruce this number but can not increase it.

Any ideas or suggestions on this ?

**Comment by rhuss** [comment] 2015-03-13 12:09
For a quick workaround with jolokia 1.2.2 and 1.2.3 you can change the `maxCollectionSize` hard limit:

* For the WAR agent, set init parameter `maxCollectionSize` to 0 (or a very large value)
* For the JVM agent, start the agent with `--maxCollectionSize=0` or use a property `maxCollectionSize` when using a configuration file with `--config`
* For the OSGi agent, set a bundle context property `org.jolokia.maxCollectionSize` to value 0

**Comment by davsclaus** [comment] 2015-03-16 11:14
Yay

Yeah I think increasing the default to 10000 is better. IMHO as ppl likely dont know about this limit and then instead they wonder why some data is not there. 

With ActiveMQ or Camel they can be verbose in JMX, eg for Camel a route can result in N mbeans, 1 for the route, N for its processors, N for its endpoints.

And for ActiveMQ you have a mbean per queue / topic. 

So hitting 1000 is actually common for production usage.

So having a limit of 10000 is better, but still even on the lower side. A broker could potential have many queues.

**Comment by davsclaus** [comment] 2015-03-16 11:16
I think the LIST should not have any limit by default, eg its there to list all the mbeans. Its a more special operation you know can return a lot of data. And if you want to limit it, maybe the list should have (if not already) a nice filter api so you can filter only the mbean kinds you want. And yeah maybe also a different upper limit option you can use, and then some way to know in the response if the upper limit was hit.

**Comment by rhuss** [comment] 2015-03-16 11:52
Yes, you are right, one should really exclude LIST operation from the `maxCollectionSize` and `maxObjects` from the limit check. The real problem indeed is, that there is no error indication when a collection gets truncated. For the other limits `maxDepth` and `maxObjects` a string with the error message is used for the values, but that's not so easy for collections (should one add an extra element ? What's about the type of the error ? etc. ...). (Remember, truncation for collection can happen on any level).

However, restricting LIST in the serialization is not so easy, since the serialization mechanism for a return value is completely decoupled from the actual operation.

What's about the following, super easy to implement solution: **Removing the hard limit on the collection size** (which is BTW the only hard limit currently set by default): 

* No truncation will happen by default.
* If someone want to secure a request, she can simply add `?maxCollectionSize=1000` to the request.
* If someone really needs a hard limit, he can repackage the WAR-agent or start the JVM Agent with the appropriate option.  (BTW, as far as I see, it's only the WAR agent which is affected by this issue because this is the only one with an hard limit set in the web.xml).

If there are no objections, I will choose this route, since this is the easiest, backwards compatible, solution for this pain point.

**Comment by davsclaus** [comment] 2015-03-16 12:43
+1

**Comment by davsclaus** [comment] 2015-04-28 09:37
@rhuss did you have time to work on jolokia recently?

**Comment by rhuss** [comment] 2015-05-04 14:26
I'm just back today and plan to do a release this week with the proposed fix.

**Comment by davsclaus** [comment] 2015-08-21 05:59
Fixed now

**Closed by davsclaus** 2015-08-21 05:59 UTC
