### ISSUE TITLE
connect to remote doesn't work (Failled to login, Forbidden)

### ISSUE THREAD

**Issue by btrice** [hawtio/hawtio#2415] opened 2017-12-06 11:18 UTC
Hello !
I launch hawtio with : java --add-modules java.xml.bind -jar hawtio-app-1.5.6.jar --port 8090
and i'm able to see hawtio console in localhost:8090/hawtio 
I have spring boot application that run on localhost:8080 with jolokia agent on port 9001
Jolokia work fine :  http://localhost:9001/jolokia 
{"request":{"type":"version"},"value":{"agent":"1.3.7","protocol":"7.2","config":{"agentId":"10.4.101.58-16464-3afd8154-servlet","debug":"true","agentType":"servlet"},"info":{"product":"tomcat","vendor":"Apache","version":"8.5.20"}},"timestamp":1512557239,"status":200}

I'm unable to connect to my jolokia agent on hawtio console ( It always show failled to login forbiden
<img width="944" alt="hawtio-1" src="https://user-images.githubusercontent.com/4358225/33659096-3c10dc98-da7f-11e7-81ba-33a0dd3343cc.PNG">
<img width="931" alt="hawtio" src="https://user-images.githubusercontent.com/4358225/33659107-3fe4ffca-da7f-11e7-9e4e-4c8374f7c86e.PNG">
<img width="419" alt="hawtio-3" src="https://user-images.githubusercontent.com/4358225/33659113-4469c12a-da7f-11e7-8710-6e60594ffc40.PNG">
is there anything wrong?

**Comment by btrice** [comment] 2017-12-06 11:32
After login on http://localhost:8090/hawtio/proxy/http://127.0.0.1:9001/jolokia/?maxDepth=7&maxCollectionSize=50000&ignoreErrors=false&canonicalNaming=false
It work fine.

**Comment by tadayosi** [comment] 2017-12-07 23:53
Have you added the following to the spring-boot app's `application.properties`?

    endpoints.jolokia.sensitive = false

If you haven't, what happens when you add it?

**Comment by btrice** [comment] 2017-12-08 13:39
Hi @tadayosi,
I put endpoints.jolokia.sensitive = false and hawtio show new error box.

<img width="562" alt="hawtio-4" src="https://user-images.githubusercontent.com/4358225/33768214-747bfd4a-dc25-11e7-936c-be2981bee289.PNG">

My application.properties contains :
jolokia.config.debug=false
endpoints.jolokia.sensitive = false
endpoints.jolokia.enabled=true
endpoints.jolokia.path=/jolokia
spring.jmx.enabled=true
endpoints.jmx.enabled=true
management.port=9001
management.address=127.0.0.1

**Comment by btrice** [comment] 2017-12-08 13:40
Hi @tadayosi,
I put endpoints.jolokia.sensitive = false and hawtio show new error box.
<img width="562" alt="hawtio-4" src="https://user-images.githubusercontent.com/4358225/33768291-bb7da982-dc25-11e7-976d-ae1a4b03aaef.PNG">

My application.properties contains : 
jolokia.config.debug=false
endpoints.jolokia.sensitive = false
endpoints.jolokia.enabled=true
endpoints.jolokia.path=/jolokia
spring.jmx.enabled=true
endpoints.jmx.enabled=true
management.port=9001
management.address=127.0.0.1

**Comment by tadayosi** [comment] 2017-12-12 10:03
It works just fine in my env. Are you securing your spring-boot app with any authentication?

It's possible that some browser cache is doing something wrong, so it's worth changing browser, clearing caches, or using incognite mode.

**Comment by btrice** [comment] 2017-12-12 10:49
Hi 
Sorry for my previous comment but i got a same error after clearing caches, changing browser or using incognite mode..
Are you securing your spring-boot app with any authentication? Yes.
After login on http://localhost:8090/hawtio/proxy/http://127.0.0.1:9001/jolokia/?maxDepth=7&maxCollectionSize=50000&ignoreErrors=false&canonicalNaming=false
It work fine without ask for login

**Comment by tadayosi** [comment] 2017-12-13 01:13
Hi @btrice,

OK, then I think hawtio-app.jar needs `-Dhawtio.authenticationEnabled=true` to enable its authentication as well. However, AFAIK there is a problem and currently no way to customise the authentication for hawtio-app.jar. I will tackle this issue later.

In the meantime, I think the easiest way for you to use hawtio with Spring Boot app is embedding hawtio within the app and using it like spring-boot-actuator. You can embed hawtio just by adding this to pom.xml:

```
    <dependency>
      <groupId>io.hawt</groupId>
      <artifactId>hawtio-springboot</artifactId>
      <version>1.5.6</version>
    </dependency>
```

Will you try that?  For more info, please have a look at examples:
https://github.com/hawtio/hawtio/tree/master/hawtio-sample-springboot-authentication
https://github.com/hawtio/hawtio/tree/master/hawtio-sample-springboot

**Comment by btrice** [comment] 2017-12-13 08:33
Hi @tadayosi ,
I used hawtio-app.jar with `-Dhawtio.authenticationEnabled=true` but i got the same error. Thank you for your suggestions it work fine with `hawtio-springboot dependency` or `hawtio-web dependency` with tomcat .
However, we have multiple application and we want to use one server for hawtio to be able to monitor all those application.
We also use camel with spring boot.

**Comment by evazquezma** [comment] 2018-02-03 18:34
Hi

I,m having a very similar problem. 
In my case I have a jolokia war agent running in a JBoss server. When I went to [http://192.168.56.101:80/jolokia](http://192.168.56.101:80/jolokia) I  received the jolokia "home" info: 
`{"timestamp":1517685884,"status":200,"request":{"type":"version"},"value":...`

I also started hawtio as an executable jar:
`java -Dhawtio.authenticationEnabled=false -Dhawtio.offline=true -jar hawtio-app-1.5.6.jar`

When I tried to connect to the jolokia agent, a login page is prompted. What login is that?
I didn´t see any log traces neither in hawtio console nor in Jboss server.

In the browser console I do see Forbidden calls to URLS like [http://localhost:8080/hawtio/proxy/http://192.168.56.101:80/jolokia/list/hawtio/type=security,name=RBACRegistry?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false](http://localhost:8080/hawtio/proxy/http://192.168.56.101:80/jolokia/list/hawtio/type=security,name=RBACRegistry?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false)
or
[http://localhost:8080/hawtio/proxy/http://192.168.56.101:80/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false](http://localhost:8080/hawtio/proxy/http://192.168.56.101:80/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false)

Thanks

**Comment by evazquezma** [comment] 2018-02-03 18:49
Sorry
Just after posted this I found the solution: **jawtio.proxyWhitelist** 

> hawtio 1.5.0 - Comma-separated whitelist for target hosts that the remote JVM connect plugin ProxyServlet can connect to (default localhost, 127.0.0.1). All hosts that are not listed in this whitelist are denied to connect for security reasons. This option can be set to * to restore old behavior and whitelist all hosts. Prefixing an element of the list with "r:" allows to define a regexp (example: localhost,r:myservers[0-9]+.mydomain.com)

**Comment by checomar** [comment] 2018-10-12 17:46
@btrice assuming you were running the standalone hawt.io app, I have successfully connected to an AWS hosted Springboot 2.0 app by starting the app like this:
`java -Dhawtio.proxyWhitelist='*' -jar hawtio-app-2.0.3.jar --port 8090`
No annoying/blocking login dialogue control to deal with 

Cheers!

**Comment by tadayosi** [comment] 2019-12-17 03:37
Looks like the issue is resolved. Let's close it.

**Closed by tadayosi** 2019-12-17 03:37 UTC
