### ISSUE TITLE
There is no Dashboard tab in Karaf 3.0.3 + hawtio 1.4.47

### ISSUE THREAD

**Issue by netudima** [hawtio/hawtio#1916] opened 2015-03-05 15:41 UTC
The tab is available in Karaf 3.0.3 + hawtio 1.4.38 but absent in Karaf 3.0.3 + hawtio since 1.4.39

**Comment by davsclaus** [comment] 2015-04-27 14:38
Duplicate of #1926

**Closed by davsclaus** 2015-04-27 14:38 UTC
Labels: karaf
